- hosts: all
  vars_files: 
   - /mnt/particion/vagrant/playbooks/kube_deployment/vars/vars.yaml
  become: true
  remote_user: "{{ user }}"

  tasks:
  - name: Disabling swap
    shell: sudo swapoff -a

  - name: Initializing pod network
    shell: sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.0.102 --apiserver-cert-extra-sans=192.168.0.102
    when: ansible_facts['nodename'] == 'master'

  - name: kube directory
    file:
     path: /home/vagrant/.kube
     owner: vagrant
     group: vagrant
     state: directory

  - name: kube config file
    shell: sudo cp /etc/kubernetes/admin.conf /home/vagrant/.kube/config && chown -R vagrant:vagrant /home/vagrant/.kube
    when: ansible_facts['nodename'] == 'master'

  - name: set env KUBECONFIG
    shell: export KUBECONFIG=$HOME/.kube/config

  - name: Deploying flannel network driver
    shell: cd /home/vagrant && echo "sudo kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml" >> flannel.sh && chmod +x flannel.sh && ./flannel.sh
    when: ansible_facts['nodename'] == 'master'

  - name: token creation
    shell: kubeadm token create --print-join-command
    register: kubecommand
    when: ansible_facts['nodename'] == 'master'
  
#  - name: set join command
#    set_fact:
#     join_command: "{{ kubecommand.stdout }}"
#    when:  ansible_facts['nodename'] == 'master'

  - name: kubejoin
    shell: "{{ kubecommand }}"
    when: ansible_facts['nodename'] != 'master'
    

    #DONE fix when conditionals 
    #DONE init kubernetes to get the config file and do the copy task  
    #TODO join nodes to the cluster
    #TODO fix flannel network through ansible shell