- hosts: master
  vars_files: 
  - /mnt/particion/vagrant/playbooks/rancher_deployment/vars/vars.yaml
  become: true
  remote_user: "{{ user }}"
  tasks:
  - name: Master deployment
    community.general.docker_container:
     name: master
     state: started
     image: rancher/rancher
     detach: yes
     interactive: yes
     ports:
     - "80:80"
     - "443:443"
     restart_policy: unless-stopped
     privileged: yes
